---
output: github_document
---


# Advanced R

### Course Description

Welcome to Advanced Analytics with R\! This short course builds onto the [Intro to R](https://github.com/uc-r/Intro-R) 
and [Intermediate R](https://github.com/uc-r/Intermediate-R) courses and provides 
a hands-on approach to applying advanced analytic techniques with the R programming language. In this course you will gain deeper knowledge around the analytic modeling process and apply various supervised and unsupervised machine learning algorithms. The
following is an outline of the material covered in this training:

**Day 1**

| Topic                                 |     Time      |
| :------------------------------------ | :-----------: |
| Breakfast / Social time               |  8:00 - 9:00  |
| Getting started                       |  9:00 - 9:45  |
| [Unsupervised modeling](https://uc-r.github.io/Advanced-R/02-unsupervised-learning.html) |  9:45 - 10:45 |
| Break                                 | 10:45 - 11:00 |
| [Supervised modeling process](https://uc-r.github.io/Advanced-R/03-supervised-modeling-process.html)           | 11:00 - 12:00 |
| Lunch                                 | 12:00 - 1:00  |
| [Feature & target engineering](https://uc-r.github.io/Advanced-R/04-engineering.html) |  1:00 - 2:00  |
| [Regression & cousins](https://uc-r.github.io/Advanced-R/05-regression.html) |  2:00 - 4:00  |
| Q\&A                                  |  4:00 - 4:30  |

**Day 2**

| Topic                                      |     Time      |
| :----------------------------------------- | :-----------: |
| Breakfast / Social time                    |  8:00 - 9:00  |
| [Decision trees, bagging, & random forests](https://uc-r.github.io/Advanced-R/06-random-forest.html)  |  9:00 - 11:00 |
| [Gradient boosting machines](https://uc-r.github.io/Advanced-R/07-gbms.html)  | 11:00 - 12:00 |
| Lunch                                      | 12:00 - 1:00  |
| Stacked models & autoML                    |  1:00 - 2:30  |
| Interpretable machine learning             |  2:45 - 4:00  |
| Q\&A                                       |  4:00 - 4:30  |

___Schedule is still being refined and is subject to change; however, the topics should remain the same.___

### Course Preparation

To prepare for this course please complete the following ***prior*** to
the day of class:

1.  Download the class material at [TBD]().
    This will provide you with the data and R scripts to follow along
    during class.

2.  All slides are available via the hyperlinks in the schedule above so
    that you can follow along.

3.  Please have the following versions of R and RStudio installed. If
    you have an earlier version of R that is at least version 3.4.5 or
    later you should be ok but its best to be as current as possible.
    
      - R: 3.5.1 \[[download latest
        version](https://cran.r-project.org/)\]
      - RStudio: 1.1.463 \[[download latest
        version](https://www.rstudio.com/products/rstudio/download/#download)\]
        
4. This course makes ___strong___ assumptions about your prior knowledge such as
   your ability to define functions, manage R objects, control the flow of a program, 
   and other basic tasks. To ensure your success, be sure that you have reviewed 
   and are comfortable with the material covered in the [Intro to R](https://github.com/uc-r/Intro-R) 
   and [Intermediate R](https://github.com/uc-r/Intermediate-R) courses. 
   
If you have any specific questions prior to the class you can reach out to me 
(Brad Boehmke) directly at [bradleyboehmke@gmail.com](mailto:bradleyboehmke@gmail.com).